### ISSUE TITLE
Enable adding gear to existing pro

### ISSUE THREAD

**Issue by kaseyalusi** [cshey15/ProGear#3]
The single pro view should have a button that brings up a modal to add (existing) gear objects to the pros gearlist.

**Comment by cshey15** [comment]
currently working on this

**Comment by cshey15** [comment]
Initial commit https://github.com/cshey15/ProGear/commit/2ea6d47f1bf6f2c69e0fd6904a695b9e75fa82f0

**Comment by cshey15** [comment]
Is it better to close this issue and open another one for styling, or to just track in one issue?

**Comment by kaseyalusi** [comment]
I would vote to open another one for styling if the functionality is in.
